sudo: false # for speed up the build
language: python
services:
  - docker
python:
  - 3.8
install:
  - pip install -r ./requirements.txt
  - pip install -r .devcontainer/requirements.test.txt
scripts:
  - pytest --cov=./jquest
#after_success:
#  - codecov
deploy:
  provider: script
  script: bash ./scripts/docker_push.sh
  on:
    branch: master
