sudo: false # for speed up the build
language: python
services:
  - docker
install: sudo apt-get -y install jq sed curl
before_script:
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - mkdir -p ~/.docker
  - echo '{"experimental":"enabled"}' >! $HOME/.docker/config.json
  - sudo service docker restart
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
python:
  - 3.8
install:
  - pip install -r ./requirements.txt
  - pip install -r .devcontainer/requirements.test.txt
scripts:
  - pytest --cov=./jquest
#after_success:
#  - codecov
deploy:
  provider: script
  script: bash ./scripts/docker_push.sh
  on:
    branch: master
